### PR TITLE
Add branch protection rule for main branch

### PR DESCRIPTION
**Pull request by coderdjw**
Followed doc: https://otterdog.readthedocs.io/en/stable/reference/organization/repository/branch-protection-rule/ and added branch protection rule for main branch of Symphony repo,

-   dismisses_stale_reviews: true,
-   requires_pull_request: true,
-   required_approving_review_count: 1,
-   requires_status_checks: true,
-   requires_strict_status_checks: true,
-   requires_conversation_resolution: true,

### CODE REVIEW

**Review by Haishi2016 — APPROVED** [review]

**Review by netomi — APPROVED** [review]

**Comment by netomi** [comment]
if you assign a project lead as reviewer and he / she approves, you can auto merge such changes.

**Comment by netomi** [comment]
fyi: I fixed your custom branch protection rule in this PR https://github.com/eclipse-symphony/.eclipsefdn/pull/3

I missed that you do not inherit from the default config in my original review. In general it is advised to always inherit from the default config, as otherwise, behavior might be undefined.

**Comment by coderdjw** [comment]
> fyi: I fixed your custom branch protection rule in this PR #3
> 
> I missed that you do not inherit from the default config in my original review. In general it is advised to always inherit from the default config, as otherwise, behavior might be undefined.

Got it, @netomi , thanks for helping fix the required checks. What is the proper way to inherit the default config?

**Comment by netomi** [comment]
each resource has its template function defined in the default config. So you should call that function to set all values to its defaults and then override as needed, like in your case with the branch protection rule now.

**Pull request merged**
