### PR TITLE
enable static pages

### PR DESCRIPTION
**Pull request by Haishi2016**

### CODE REVIEW

**Comment by netomi** [comment]
we strongly recommend to use GH Pages with workflow publishing as this does not require committing the actual website content to a separate branch, but its up to you ofc.

Example workflow to publish to GH Pages using the 'workflow' method:

https://github.com/eclipse-csi/security-handbook/blob/main/.github/workflows/build-page.yml

**Comment by Haishi2016** [comment]
> we strongly recommend to use GH Pages with workflow publishing as this does not require committing the actual website content to a separate branch, but its up to you ofc.
> 
> Example workflow to publish to GH Pages using the 'workflow' method:
> 
> https://github.com/eclipse-csi/security-handbook/blob/main/.github/workflows/build-page.yml

We will set up build pipelines to publish to symphony-website as a submodule mapped to docs-site/public folder. Our challenge is that we also want to publish a landing page site, but since GH allows only one static site per repo, our plan is to publish the landing page site directly from symphony/landing/public folder.

**Review by netomi — APPROVED** [review]

**Comment by netomi** [comment]
First time we ran into this issue with the path, there is apparently a limitation for the allowed values, will add a validation rule for that.

We will need to adjust the path, let me know what you want and I will adjust accordingly.

**Comment by Haishi2016** [comment]
> First time we ran into this issue with the path, there is apparently a limitation for the allowed values, will add a validation rule for that.
> 
> We will need to adjust the path, let me know what you want and I will adjust accordingly.

I see the PR has been merged. I think we should do it properly to have a separate docs repo so that we publish landing page to the symphony-website repo and docs to the docs repo. I've created another ticket to create the docs repo under the eclipse-symphony org

**Comment by netomi** [comment]
perfect, makes sense.

**Comment by netomi** [comment]
reverted the change for GH Pages for the symphony repository and created a new PR to add a new docs repo.

**Pull request merged**
